# Generated by Django 3.0.8 on 2020-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='movie',
        ),
        migrations.AddField(
            model_name='customer',
            name='movies',
            field=models.ManyToManyField(to='movieApp.Movie'),
        ),
    ]
